### ISSUE TITLE
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接

### ISSUE THREAD

**Issue by Teng-Pan** [dazhi0619/CS305-23S-Assignment1#13]
when I use debug mode, the code runs correctly, but if I run at commond line, error occurred. What should I do?

![JX1}X()SHBJK7N@YZEIC0VW](https://user-images.githubusercontent.com/85722183/227768867-20ac96b5-a3cf-4d17-ac7e-023cb55671b8.png)
![I {3 PYEBW08( M92S{ H@1](https://user-images.githubusercontent.com/85722183/227768902-847282fb-51b3-4e09-8dac-9720cdc265a9.png)

**Comment by wyatt-feng** [comment]
I'm not quite sure, but it seems that the server closes the control connection when there is a connection error. Since you have already successfully produced a test result with a full mark and there is no problem running in PyCharm debug mode, you can leave the problem as it is. You can still look into it if you want and begin with the difference between the debug mode and the command line or begin with the exception handling process of the server.

**Comment by Teng-Pan** [comment]
I try again many times on the command line. Sometimes it runs correctly, sometimes not. It may not be related to debug mode. I think I can write this problem in the report and remind SAs run again if error occurs during scoring. Is it ok?
![W`FC7@50ZW773V % VNO V](https://user-images.githubusercontent.com/85722183/227864925-de5edbc4-88fb-4ed5-a9a1-7d40b8f813c1.png)
![J1CYZ`TL5HO({K23B7OWZB](https://user-images.githubusercontent.com/85722183/227864946-ec4150e2-6585-4355-8138-8b6c5dc840a3.png)

**Comment by wyatt-feng** [comment]
It *could* be because you did not wait for enough time before two test processes. You can write this in your report, although it does not affect your score and we typically will not run your code when assessing your implementation.
